spring:
  datasource:
    url: jdbc:derby:app;create=true
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.DerbyTenSevenDialect
      entitymanager.packages.to.scan: geo.db.entity
      ddl-auto: update
      show_sql: true
  main:
    banner-mode: "off"


server:
  port: 8181




management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  
